version: "3.9"
  
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: django_mongodb_docker
    ports:
      - 27017:27017
  web:
    build: .
    restart: always
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - migration  

  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/code
    links:
      - mongodb
    depends_on:
      - mongodb
  client:
    build: ./leaderboard-frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./leaderboard-frontend:/app
    depends_on:
      - web