# Generated by Django 3.0.5 on 2020-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team1', models.CharField(max_length=30)),
                ('team2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
